// start
let input = document.querySelector( "input" );
let span = document.querySelector( ".result" );
let btn = document.querySelector( ".btn" );
let h = document.querySelector( " h4" );

const elments = {
  // HTML
  "a": "Defines a hyperlink",
  "bdo": " 	Overrides the current text direction",
  "abbr": "Defines an abbreviation or an acronym",
  "acronym": " 	<span>	Not supported in HTML5.</span> Use &lt;abbr&gt; instead Defines an acronym",
  "address": " 	Defines contact information for the author/owner of a document",
  "applet": "<span>	Not supported in HTML5.</span> Use <embed> or <object> instead . Defines an embedded applet",
  "area": " 	Defines an area inside an image-map",
  "article": " 	Defines an article",
  "aside": "Defines content aside from the page content",
  "audio": " 	Defines sound content",
  "b": " 	Defines bold text",
  "base": " 	Specifies the base URL/target for all relative URLs in a document",
  "basefont": " 	<span>	Not supported in HTML5.</span> Use CSS instead . Specifies a default color, size, and font for all text in a document",
  "bdi": " 	Isolates a part of text that might be formatted in a different direction from other text outside it",
  "bdo": " 	Overrides the current text direction",
  "big": " 	Not supported in HTML5. Use CSS instead . Defines big text",
  "blockquote": "Defines a section that is quoted from another source",
  "body": " 	Defines the document's body",
  "br": " 	Defines a single line break",
  "button": " 	Defines a clickable button",
  "canvas": " 	Used to draw graphics, on the fly, via scripting (usually JavaScript)",
  "caption": " 	Defines a table caption",
  "center": " 	<span>Not supported in HTML5.</span> Use CSS instead . Defines centered text",
  "cite": " 	Defines the title of a work",
  "code": " 	Defines a piece of computer code",
  "col": " 	Specifies column properties for each column within a &lt;colgroup&gt; element ",
  "colgroup": " 	Specifies a group of one or more columns in a table for formatting",
  "data": " 	Links the given content with a machine-readable translation",
  "datalist": " 	Specifies a list of pre-defined options for input controls",
  "dd": " 	Defines a description/value of a term in a description list",
  "dl": " 	Defines text that has been deleted from a document",
  "detalis": " 	Defines additional details that the user can view or hide",
  "dfn": "Represents the defining instance of a term",
  "dialog": " 	Defines a dialog box or window",
  "dir": " 	<span>	Not supported in HTML5.</span> Use &lt;ul&gt; instead . Defines a directory list",
  "div": " 	Defines a section in a document",
  "dlist": " 	Defines a description list",
  "dt": " 	Defines a term/name in a description list",
  "em": " 	Defines emphasized text ",
  "embed": " 	Defines a container for an external (non-HTML) application",
  "fielset": " 	Groups related elements in a form",
  "figcaption": " 	Defines a caption for a &lt;figure&gt; element",
  "figure": " 	Specifies self-contained content",
  "font": " 	<span>	Not supported in HTML5.</span> Use CSS instead . Defines font, color, and size for text",
  "footer": " 	Defines a footer for a document or section",
  "form": " 	Defines an HTML form for user input",
  "frame": " 	<span>	Not supported in HTML5.</span> Defines a window ( a frame ) in a frameset",
  "frameset": " 	<span>	Not supported in HTML5.</span> Defines a set of frames",
  "h": " 	Defines HTML headings",
  "head": " 	Defines information about the document",
  "header": " 	Defines a header for a document or section",
  "hr": "Defines a thematic change in the content",
  "html": " 	Defines the root of an HTML document",
  "i": " 	Defines a part of text in an alternate voice or mood",
  "iframe": " 	Defines an inline frame",
  "img": " 	Defines an image",
  "input": " 	Defines an input control",
  "ins": " 	Defines a text that has been inserted into a document",
  "kbd": " 	Defines keyboard input",
  "label": " 	Defines a label for an <input> element",
  "legend": " 	Defines a caption for a &lt;fieldset&gt; element",
  "li": " 	Defines a list item",
  "link": " 	Defines the relationship between a document and an external resource (most used to link to style sheets)",
  "main": " 	Specifies the main content of a document",
  "map": " 	Defines a client-side image-map",
  "mark": " 	Defines marked/highlighted text",
  "meta": " 	Defines metadata about an HTML document",
  "meter": " 	Defines a scalar measurement within a known range (a gauge)",
  "nav": " 	Defines navigation links",
  "noframes": " <span>	Not supported in HTML5.</span> Defines an alternate content for users that do not support frames",
  "noscript": "Defines an alternate content for users that do not support client-side scripts",
  "object": "Defines an embedded object",
  "ol": "Defines an ordered list",
  "optgroup": "Defines a group of related options in a drop-down list",
  "option": "Defines an option in a drop-down list",
  "output": "Defines the result of a calculation",
  "p": "Defines a paragraph",
  "param": "Defines a parameter for an object",
  "picture": "Defines a container for multiple image resources",
  "pre": "Defines preformatted text",
  "progress": "Represents the progress of a task",
  "q": " 	Defines a short quotation",
  "rp": "Defines what to show in browsers that do not support ruby annotations",
  "rt": "Defines an explanation/pronunciation of characters (for East Asian typography)",
  "ruby": "Defines a ruby annotation (for East Asian typography)",
  "s": " 	Defines text that is no longer correct",
  "samp": "Defines sample output from a computer program",
  "script": " 	Defines a client-side script",
  "section": "Defines a section in a document",
  "select": "Defines a drop-down list",
  "small": "Defines smaller text",
  "source": "Defines multiple media resources for media elements (&lt;video&gt; and <audio>)",
  "span": "Defines a section in a document",
  "strike": " 	<span>Not supported in HTML5.</span> Use &lt;del&gt; or &lt;s&gt; instead . Defines strikethrough text",
  "strong": " 	Defines important text",
  "style": " 	Defines style information for a document",
  "sub": "Defines subscripted text",
  "summary": "Defines a visible heading for a <details> element",
  "sup": "Defines superscripted text",
  "svg": "Defines a container for SVG graphics",
  "table": "Defines a table",
  "tbody": "Groups the body content in a table",
  "td": "Defines a cell in a table",
  "template": "Defines a template",
  "textarea": "Defines a multiline input control (text area)",
  "tfoot": " 	Groups the footer content in a table",
  "th": "Defines a header cell in a table",
  "thead": " 	Groups the header content in a table",
  "time": "Defines a date/time",
  "title": "Defines a title for the document",
  "tr": "Defines a row in a table",
  "track": "Defines text tracks for media elements (&lt;video&gt; and &lt;audio&gt;)",
  "tt": " 	<span>Not supported in HTML5</span> Use CSS instead.Defines teletype text",
  "u": "Defines text that should be stylistically different from normal text",
  "ul": "Defines an unordered list",
  "var": "Defines a variable",
  "video": "Defines a video or movie",
  "wbr": "Defines a possible line-break",
  "align-content": "Specifies the alignment between the lines inside a flexible container when the items do not use all available space",
  "align-items": " 	Specifies the alignment for items inside a flexible container",
  "align-self": "Specifies the alignment for selected items inside a flexible container",
  "all": "Resets all properties (except unicode-bidi and direction)",
  "animation": "A shorthand property for all the animation-* properties",
  "animation-delay": "Specifies a delay for the start of an animation",
  "animation direction": "Specifies whether an animation should be played forwards, backwards or in alternate cycles",
  "animation-duration": "Specifies how long an animation should take to complete one cycle",
  "animation-fill-mode": "Specifies a style for the element when the animation is not playing (before it starts, after it ends, or both)",
  "animation-iteration-count": "Specifies the number of times an animation should be played",
  "animation-play state": "Specifies whether the animation is running or paused",
  "animation-name": " 	Specifies a name for the @keyframes animation",
  "animation-timing-function": " 	Specifies the speed curve of an animation",
  "backface-visibility": "Defines whether or not the back face of an element should be visible when facing the user",
  "background": "A shorthand property for all the background-* properties",
  "background-attachment": "Sets whether a background image scrolls with the rest of the page, or is fixed",
  "background-blend-mode": "Specifies the blending mode of each background layer (color/image)",
  "background-clip": "Defines how far the background (color or image) should extend within an element",
  "background-color": "Specifies the background color of an element",
  "background-image": "Specifies the origin position of a background image"
};

window.onload = function() {
  input.focus``;
};
input.oninput = function() {

  span.innerHTML = input.value;

  for ( let [ k, v ] of Object.entries( elments ) ) {
    if ( k === input.value ) {
      span.innerHTML = `<h4>[${ k }]</h4>  ${ v }`;
    } 
  };
  if ( input.value === "" ) {
    span.innerHTML = "Result"
  }
};
btn.onclick = function() {
  input.value = "";
  span.innerHTML = "Deleted"
};